### PR TITLE
support Symfony 2.7 Config and Yaml components

### PR DESCRIPTION
**Pull request by relvinhas**
Prevents deprecation messages.
Tests pass

### CODE REVIEW

**Comment by relvinhas** [comment]
@henrikbjorn any feedback on this PR?

**Comment by henrikbjorn** [comment]
Thanks :)

**Comment by relvinhas** [comment]
@henrikbjorn you are welcome. Can you tag a new stable release?

**Comment by relvinhas** [comment]
Also, flint/flint could use the latest tagged version instead of ~0.4.
Should I open an issue and PR?

**Comment by henrikbjorn** [comment]
@relvinhas it cant as the 1.x branch requires 5.4 which is higher than flint. Was really hoping Silex 2.0 would soon come out and flint would be Brick instead.

Is it possible to port it to the 0.x branch ?

**Pull request merged**
